Revert to snakemake v5.26.1 due to bug
Not sure if this is a snakemake bug, or if the new version exposed a bug in (at
least) the non_10x.snakefile; backtrace ended with:

File "/usr/local/lib/python3.8/site-packages/snakemake/io.py", line 563, in check_broken_symlink
  if not self.exists_local and os.lstat(self.file):
FileNotFoundError: [Errno 2] No such file or directory:
  '/sequencing/source/201028_NB551608_0175_AHY2MVAFXY/status/demultiplex.processed'